
package br.petrik.EntregaWSclient;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaWS", targetNamespace = "http://webservices.petrik.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaWS {


    /**
     * 
     * @throws IOException_Exception
     * @throws ServletException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "enviarEntrega", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.EntregaWSclient.EnviarEntrega")
    @ResponseWrapper(localName = "enviarEntregaResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.EntregaWSclient.EnviarEntregaResponse")
    public void enviarEntrega()
        throws IOException_Exception, ServletException_Exception
    ;

}
