
package br.petrik.ProdutoWSclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoWS", targetNamespace = "http://webservices.petrik.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.petrik.ProdutoWSclient.Produto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTodosService", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.ListarTodosService")
    @ResponseWrapper(localName = "listarTodosServiceResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.ListarTodosServiceResponse")
    public List<Produto> listarTodosService();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.petrik.ProdutoWSclient.Produto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProdutoService", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.GetProdutoService")
    @ResponseWrapper(localName = "getProdutoServiceResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.GetProdutoServiceResponse")
    public Produto getProdutoService(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarService", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.SalvarService")
    @ResponseWrapper(localName = "salvarServiceResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.SalvarServiceResponse")
    public void salvarService(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletarService", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.DeletarService")
    @ResponseWrapper(localName = "deletarServiceResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.DeletarServiceResponse")
    public void deletarService(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "alterarService", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.AlterarService")
    @ResponseWrapper(localName = "alterarServiceResponse", targetNamespace = "http://webservices.petrik.br/", className = "br.petrik.ProdutoWSclient.AlterarServiceResponse")
    public void alterarService(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0);

}
